all:
  hosts:
    tableTopNode1:
      ansible_python_interpreter: /usr/bin/python3
      ansible_host: 10.5.0.101
    tableTopNode2:
      ansible_python_interpreter: /usr/bin/python3
      ansible_host: 10.5.0.102
    tableTopNode3:
      ansible_python_interpreter: /usr/bin/python3
      ansible_host: 10.5.0.103

  children:
    new_vaults:
      hosts:
        tableTopNode1:
        tableTopNode2:
        tableTopNode3:

    remove_vaults:
      hosts:
        tableTopNode1:
        tableTopNode2:
        tableTopNode3:
