all:
  hosts:
    tableTopNode1:
      ansible_host: 192.168.122.100
    tableTopNode2:
      ansible_host: 192.168.122.101
    tableTopNode3:
      ansible_host: 192.168.122.102

  children:
    new_vaults:
      hosts:
        tableTopNode1:
        tableTopNode2:
        tableTopNode3:

    remove_vaults:
      hosts:
        tableTopNode1:
        tableTopNode2:
        tableTopNode3:
