- name: Unmount tmpfs if mounted
  mount:
    path: "{{ vault_dir }}/secrets"
    state: unmounted
  ignore_errors: true

- name: Remove tmpfs mount from fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^tmpfs\s+{{ vault_dir }}/secrets\s+tmpfs'
    state: absent
  notify: Reload systemd
# - name: Unmount vault dir if mounted
#   mount:
#     path: "{{ vault_dir }}"
#     state: unmounted
#   ignore_errors: true

# - name: Remove vault dir entry from fstab
#   lineinfile:
#     path: /etc/fstab
#     regexp: '^\S+\s+{{ vault_dir }}\s+'
#     state: absent

# - name: Remove vault directory
#   file:
#     path: "{{ vault_dir }}"
#     state: absent
- name: Find all contents of the vault directory
  find:
    paths: "{{ vault_dir }}"
    file_type: any
    recurse: yes
  register: vault_dir_contents

- name: Remove all contents of the vault directory
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ vault_dir_contents.files }}"
