- name: Copy ca.pem
  copy:
    src: "{{ ca_path }}"
    dest: "{{ vault_dir }}/authorities/ca.pem"
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_authorities_group }}"
    mode: "0740"

- name: Copy ca cert into system store
  become: true
  copy:
    remote_src: true
    src: "{{ vault_dir }}/authorities/ca.pem"
    dest: /usr/local/share/ca-certificates/vault-ca.crt
    owner: root
    group: root
    mode: "0640"
