- name: Ensure vault agent group exists
  group:
    name: "{{ vault_agent_group }}"
    state: present

- name: Ensure vault agent navigational group exists
  group:
    name: "{{ vault_agent_navigational_group }}"
    state: present

- name: Ensure vault agent authorities group exists
  group:
    name: "{{ vault_agent_authorities_group }}"
    state: present

- name: Ensure vault agent user exists
  user:
    name: "{{ vault_agent_user }}"
    groups:
      - "{{ vault_agent_group }}"
      - "{{ vault_agent_navigational_group }}"
      - "{{ vault_agent_authorities_group }}"
    state: present
