- name: Include apt tasks
  import_tasks: apt.yaml

- name: Include create users tasks
  import_tasks: createUsers.yaml

- name: Include mkdirs tasks
  import_tasks: mkdirs.yaml

- name: Include binaries tasks
  import_tasks: binaries.yaml
