# Main paths
- name: Create vault scripts directory
  file:
    path: "{{ vault_dir }}/scripts"
    state: directory
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_navigational_group }}"
    mode: "0710"

- name: Create vault templates directories
  file:
    path: "{{ vault_dir }}/templates"
    state: directory
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_navigational_group }}"
    mode: "0710"

- name: Create vault agents directories
  file:
    path: "{{ vault_dir }}/agents"
    state: directory
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_navigational_group }}"
    mode: "0710"

- name: Create vault authorities directories
  file:
    path: "{{ vault_dir }}/authorities"
    state: directory
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_navigational_group }}"
    mode: "0710"

# bin
- name: Create {{ vault_dir }}/bin directory
  file:
    path: "{{ vault_dir }}/bin"
    state: directory
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_navigational_group }}"
    mode: "0710"

- name: Add {{ vault_dir }}/bin to PATH
  lineinfile:
    path: /etc/profile.d/vault_path.sh
    line: "export PATH=$PATH:{{ vault_dir }}/bin"
    create: yes
    mode: "0755"

# certs
- name: Set ownership and permissions on {{ vault_dir }}/secrets
  file:
    path: "{{ vault_dir }}/secrets"
    state: directory
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_navigational_group }}"
    mode: "0710"

- name: Add tmpfs mount to fstab (if not already present)
  lineinfile:
    path: /etc/fstab
    regexp: '^tmpfs\s+{{ vault_dir }}/secrets\s+tmpfs'
    line: "tmpfs {{ vault_dir }}/secrets tmpfs nodev,nosuid,noexec,size=32K 0 0"
    state: present
    create: yes
    backup: yes

- name: Ensure tmpfs is mounted
  mount:
    path: "{{ vault_dir }}/secrets"
    src: tmpfs
    fstype: tmpfs
    opts: nodev,nosuid,noexec,size=32K
    state: mounted

- name: Set ownership on mounted tmpfs
  file:
    path: "{{ vault_dir }}/secrets"
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_navigational_group }}"
    mode: "0710"

- name: Copy ca.pem
  copy:
    src: "{{ ca_path }}"
    dest: "{{ vault_dir }}/authorities/ca.pem"
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_authorities_group }}"
    mode: "0740"

- name: Copy ca cert into system store
  become: true
  copy:
    remote_src: true
    src: "{{ vault_dir }}/authorities/ca.pem"
    dest: /usr/local/share/ca-certificates/vault-ca.crt
    owner: root
    group: root
    mode: "0640"

- name: Update the system ca certificates
  become: true
  command: update-ca-certificates
  args:
    creates: /etc/ssl/certs/vault-ca.pem
